config/routes.rb
FlightDog::Application.routes.draw do

  get "suggestions/new"
  

  resources :suggestions, :only => [:new, :create]
  resources :flights
  resources :scrapes
  

  match '/home', :to => 'pages#home'
  match 'about', :to => 'pages#about'
  match 'help', :to => 'pages#help'
  match '/contact', :to => 'suggestions#new'
  match '/flights/list', :to => 'flights#list'
  match '/test', :to => 'pages#test'
  match '/scrape', :to => 'scrapes#create'
  
  
  root :to => "pages#home"

end

app/models/flight.rb
# == Schema Information
#
# Table name: flights
#
#  id              :integer         not null, primary key
#  observation_date :datetime
#  flight_date      :date
#  origin          :string(255)
#  destination     :string(255)
#  price           :float
#  flight_number    :string(255)
#  departs         :time
#  arrives         :time
#  duration        :integer
#  seats           :integer
#  created_at      :datetime
#  updated_at      :datetime
#

class Flight < ActiveRecord::Base
  
  attr_accessible  :id, :observation_date, :flight_date, :origin, :destination, :price, :flight_number,
                  :departs, :arrives, :duration, :seats, :created_at, :updated_at, :airline
  
  AIRPORTS = ["BOS", "BWI"]
  
  def readonly?
    return false
  end
    
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController  
  
  def index
    @title = "Search Flights"
    flight_date = Date.strptime(params[:flight_date], fmt='%m/%d/%Y')    
                                                  
    @flights = Flight.find_by_sql(" SELECT DISTINCT flights.flight_date, flights.flight_number, 
                                    flights.origin, flights.destination, flights.airline FROM flights
                                    WHERE flight_date = '#{flight_date}'
                                    AND origin = '#{params[:origin]}' 
                                    AND destination = '#{params[:destination]}'
                                    AND airline = '#{params[:airline]}'")                                                  
  end
  
  def show
    @title = "Flight History"
    
    @referenceFlight = Flight.find(params[:id])
    @flights = Flight.find(:all, :conditions => { :origin => @referenceFlight.origin,
                                                :destination => @referenceFlight.destination,
                                                :flight_date => @referenceFlight.flight_date,
                                                :flight_number => @referenceFlight.flight_number,
                                                :airline => @referenceFlight.airline
                                                  })
    @chartseries = ""
    @flights.each do |f|
      @chartseries << "[#{((Time.now.to_f - f.observation_date.to_f)/86400).round(2)},#{f.price}],"
    end
  end  
  
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/flights/_flight.html.erb
<% referenceFlight = Flight.find(:first, :conditions => { :origin => flight.origin,
                                                          :flight_number => flight.flight_number,
                                                          :destination => flight.destination,
                                                          :flight_date => flight.flight_date,
                                                          :airline => flight.airline
                                                        }) %>
                                                     
                                                                                                             
<tr class="flights">
    <td><%= referenceFlight.flight_date %></td>
    <td><%= referenceFlight.departs.strftime("%H:%M") %></td>
    <td><%= referenceFlight.origin %></td>
    <td><%= referenceFlight.destination %></td>
    <td><%= link_to 'History', flight_path(referenceFlight) %></td>
  </tr>

app/views/flights/index.html.erb
<div class = "info round"> 
<table>
  <% if @flights.length != 0 %>
    <tr class = "heading">
      <td>Flight Date</td><td>Departs</td><td>Origin</td><td>Destination</td>
    </tr>
    <%= render @flights %>
  <% else %>
  <div class = "info round">
    There are no flights in our database that match your search criteria.<br><br>
    <%= link_to "Why Not?", help_path %>
  </div>  
  <% end %>
</table>
</div>

app/views/flights/show.html.erb
<% x = @chartseries[0..(@chartseries.length-2)].to_s %>
<% y = x[1..13] %>


<div id='chart_div'</div>
  

    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">
      google.load("visualization", "1", {packages:["corechart"]});
      google.setOnLoadCallback(drawChart);
      function drawChart() {
        var data = new google.visualization.DataTable();
        data.addColumn('number', 'Date');
        data.addColumn('number', 'Price');
        data.addRows([<%= x %> ]);

        var chart = new google.visualization.ScatterChart(document.getElementById('chart_div'));
        chart.draw(data, {lineWidth: 4,
                          width: 560,
                          height: 300,
                          title: 'FarePlot\'s Observations for <%= @referenceFlight.airline %> <%= @referenceFlight.flight_number %> from <%= @referenceFlight.origin %> to <%= @referenceFlight.destination %> at <%= @referenceFlight.departs.strftime("%H:%M") %> on  <%= @referenceFlight.flight_date.strftime('%A, %B %d') %>',
                          titleTextStyle: {color: '#3366CC', fontSize: '135%'},
                          vAxis: {format: '$#', title: "Observed Price"},
                          hAxis: {direction: -1, format: '# Days Ago'},
                          pointSize: 0,
                          legend: 'none' });
      }
    </script>