config/routes.rb
FlightDog::Application.routes.draw do

  get "suggestions/new"
  

  resources :suggestions, :only => [:new, :create]
  resources :flights
  resources :scrapes
  

  match '/home', :to => 'pages#home'
  match 'about', :to => 'pages#about'
  match 'help', :to => 'pages#help'
  match '/contact', :to => 'suggestions#new'
  match '/flights/list', :to => 'flights#list'
  match '/test', :to => 'pages#test'
  match '/scrape', :to => 'scrapes#create'
  
  
  root :to => "pages#home"

end

app/views/pages/about.html.erb
<div class = "info round">
  FarePlots is a tool to help you<br />
  determine the optimal time to purchase airline tickets.
  <br /><br />
  Enter the information for your flight of interest<br />
  on the home page to view the price history of that flight.
</div>

app/views/pages/help.html.erb
<div class = "info round">
  <ui class = "question">
  Why can't I find the my flight on your site?
  </ui>
  </br></br>
  <ui class = "answer">
  We're just starting out, so at this time we're only collecting information for some of the most popular AirTran and JetBlue routes. We plan on adding more routes soon. If you are interested in a particular route, please let us know using the Contact form.
  </ui>
</div>

<div class = "info round">
  <ui class = "question">
  I see my flight for a different price than your site shows. Why?
  </ui>
  </br></br>
  <ui class = "answer">
  Our pricing data comes directly from the airline websites. Different aggregators or ticketing agents may offer different prices. We strive to keep our data as accurate as possible.
  </ui>
</div>

<div class = "info round">
  <ui class = "question">
  Do I have to register or pay to use FarePlots?
  </ui>
  </br></br>
  <ui class = "answer">
  Absolutely not. FarePlots is provided entirely free of charge. If you'd like to support our site, we encourage you to use the affiliate links to buy your airline tickets. It doesn't cost you anything extra, and it helps us keep the site up and running. Also, tell your friends!
  </ui>
</div>

app/views/pages/home.html.erb
<div class = "description">  
        Enter your flight information on the right to find the price history for that flight.<br /><br />        <font class="note">Please Note:</font> We're just starting out, so for now we only have information for AirTran and Jet Blue flight between some popular destinations. We'll be adding more flights soon!<br /><br />
</div>
            

<script>
	$(function() {
		$( "#flight_date" ).datepicker({ minDate: +6, maxDate: +25, showOn: "button",
			buttonImage: "images/calendar.gif",
			buttonImageOnly: true });
	});
</script>


<% form_tag flights_path, :method => 'get' do %>
<p>  
  <%= label_tag 'airline' %>
  <%= select_tag(:airline, options_for_select([["Select Airline", "---"], ["AirTran", "AT"], ["Jet Blue", "JB"]]))%><br />
  <%= label_tag 'origin' %>
  <%= select_tag(:origin, options_for_select([["Select Origin", "---"], ["Atlanta", "ATL"], ["Boston", "BOS"], ["Baltimore", "BWI"], ["Fort Lauderdale", "FLL"], ["Long Beach", "LGB"], ["Milwaukee", "MKE"], ["Orlando", "MCO"]]))%><br />
  <%= label_tag 'destination' %>
  <%= select_tag(:destination, options_for_select([["Select Destination", "---"], ["Atlanta", "ATL"], ["Boston", "BOS"], ["Baltimore", "BWI"], ["Fort Lauderdale", "FLL"], ["Long Beach", "LGB"], ["Milwaukee", "MKE"], ["Orlando", "MCO"]]))%><br />
  <%= label_tag 'date' %>
  <%= text_field_tag(:flight_date) %><br />
  <%= submit_tag "Search", :name => nil %>
  
</p>
<% end %>

app/views/pages/scrape.html.erb
<div class = "info round">
  Finished scraping.
</div>

app/views/pages/test.html.erb
<div id="r" style="width: 560px; height: 300px;"></div>
<script type="text/javascript" charset="utf-8"> 
            $(function () {  
                // Creates canvas 640 × 480 at 10, 50
                var r = Raphael(10, 50, 640, 480);
                
                // Creates a simple line chart at 10, 10
                // width 300, height 220
                // x-values: [1,2,3,4,5], y-values: [10,20,15,35,30]
                r.g.linechart(10,10,300,220,[1,2,3,4,5],[10,20,15,35,30]);
            })
</script>