config/routes.rb
FlightDog::Application.routes.draw do

  get "suggestions/new"
  

  resources :suggestions, :only => [:new, :create]
  resources :flights
  resources :scrapes
  

  match '/home', :to => 'pages#home'
  match 'about', :to => 'pages#about'
  match 'help', :to => 'pages#help'
  match '/contact', :to => 'suggestions#new'
  match '/flights/list', :to => 'flights#list'
  match '/test', :to => 'pages#test'
  match '/scrape', :to => 'scrapes#create'
  
  
  root :to => "pages#home"

end

app/views/layouts/_footer.html.erb
<footer class="round">
	<nav class = "round">
    <ul>
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "About", about_path %></li>
      <li><%= link_to "FAQ", help_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
		</ul>
  </nav>
</footer>

app/views/layouts/_googleanalytics.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-25823313-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/layouts/_logo.html.erb
<div>
  <%= link_to image_tag("logo3.png", :alt => "Flight Dog", :class => "round", :size =>"315x420"), home_path %>
</div>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->  
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
<!--[if lt IE8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%=stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title> FarePlots: <%= @title %> </title>
		<%= csrf_meta_tag %>
		<%= render 'layouts/stylesheets'%>
    <%= javascript_include_tag :defaults %>`
    <%= javascript_include_tag "jquery-1.6.2", "application", "rails", "highcharts", "jquery-ui-1.8.16.custom.min.js" %>
    <%= stylesheet_link_tag 'cupertino/jquery-ui-1.8.16.custom.css' %>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-25823313-1']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
    </script>
	</head>
	<body>
    <div class = "container">
      <section>
        <table>
          <tr>
            <td>
              <%= render 'layouts/logo'%>
            </td>
            <td>
              <%= yield %>
            </td>
          </tr>
        </table>
			</section>
			<%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
		</div>
	</body>
</html>